appname = casdoor
httpport = 8000
runmode = prod
driver = postgres
origin = http://127.0.0.1:8000
staticBaseUrl = https://cdn.casbin.org
enableGzip = true

# Database - will be overridden by env vars in start script
dbName = casdoor
dbType = postgres
dbUser = %(ENV_PGUSER)s
dbPassword = %(ENV_PGPASSWORD)s
dbHost = %(ENV_PGHOST)s
dbPort = %(ENV_PGPORT)s
