# enable-template
# Temporal UI Config - Simple OIDC config for testing

temporalGrpcAddress: temporal:7233
port: 8080
enableUi: true
cloudUi: false
defaultNamespace: default
cors:
  cookieInsecure: true
  unsafeAllowAllOrigins: false
  allowOrigins:
    - "http://192.168.2.68:8080"
    - "http://localhost:8080"
tls:
  enableHostVerification: false
auth:
  enabled: true
  providers:
  - label: sso
    type: oidc
    providerUrl: http://casdoor:8000
    issuerUrl: http://192.168.2.68:8000
    clientId: 8269b3a04ee85269e59c
    clientSecret: 1ef7a535169058cfa0f65960036a959b390f1447
    callbackUrl: http://192.168.2.68:8080/auth/sso/callback
    useIdTokenAsBearer: true
    scopes:
      - openid
      - profile
      - email
hideLogs: false
